[colors.bright]
green = "#79c32e"

[colors.normal]
black = "#1d1f21"
blue = "#1d7dcc"
cyan = "#46a4b0"
green = "#219617"
magenta = "#a56bb5"
red = "#db2a21"
white = "#a3a6ad"
yellow = "#e8cd46"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "full"
opacity = 0.95
