alias vi='nvim'
alias upall='sudo apt update && sudo apt upgrade && flatpak update'
alias aptrm='sudo apt autoremove'
alias ytmp3='yt-dlp -f "ba" -x --audio-format mp3'
alias ls='ls --color=auto'
alias la='ls -lah --color=auto'
alias tmuxnew='tmux new -s'
alias tattach='tmux attach-session -t'

alias rm='rmtrash -Iv'
alias trm='trash-remove'
alias trl='trash-list'
alias trr='trash-restore'
alias tre='trash-empty'

alias mv='mv -iv'
alias cp='cp -iv'
alias mkdir='mkdir -v'
