format = """
$username\
[](bg:#008700 fg:#005f00)\
$hostname\
[](bg:#eaeaea fg:#008700)\
$directory\
$git_branch\
$git_status\
[](fg:#eaeaea) """

add_newline = true

[username]
show_always = true
style_user = 'bg:#005f00 fg:#ffffff'
style_root = 'bg:#005f00 fg:#ffffff'
format = '[ $user ]($style)'

[hostname]
ssh_only = false
style = 'bg:#008700 fg:#ffffff'
format = '[ $hostname ]($style)'

[directory]
style = 'bg:#eaeaea fg:#000000'
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = "../"

[git_branch]
style = 'bg:#686868 fg:#ffffff'
format = '[](bg:#686868 fg:#eaeaea)[ $branch]($style)'

[git_status]
style = 'bg:#686868 fg:#ffffff'
ahead = '△'
behind = '▽'
diverged = '○'
modified = '◔'
stashed = ''
format = '[ $all_status$ahead_behind ]($style)[](bg:#eaeaea fg:#686868)'

[line_break]
disabled = true

[package]
disabled = true

