font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0
force_ltr no
cursor #cccccc

cursor_shape block
cursor_shape_unfocused block
cursor_blink_interval 0
cursor_stop_blinking_after 0.0

scrollback_lines 5000
scrollbar never
progress_bar bottom

copy_on_select no

enable_audio_bell no
command_on_bell none

remember_window_size no
remember_window_position no
active_border_color #71d23b
hide_window_decorations no
window_title_bar top
window_padding_width 0
single_window_padding_width -1
placement_strategy top
active_border_color #71d23b

tab_bar_edge bottom
tab_bar_style powerline
tab_bar_show_new_tab_button yes
tab_powerline_style round

background #1d1f21
foreground #c5c8c6
selection_foreground none
selection_background none
background_opacity 0.95
background_blur 2

# black
color0 #1d1f21
color8 #6b6b6b

# red
color1 #db2a21
color9 #c55555

# green
color2 #219617
color10 #79c32c

# yellow
color3 #e8cd46
color11 #feca88

# blue
color4 #1d7dcc
color12 #82b8c8

# magenta
color5  #a56bb5
color13 #c28cb8

# cyan
color6  #46a4b0
color14 #82b8c8

# white
color7  #a3a6ad
color15 #f8f8f8

wayland_titlebar_color system
hide_window_decorations no
allow_hyperlinks yes
shell_integration no-cursor
