[manager]
sort_by = "natural"
sort_dir_first = true
show_symlink = true

[opener]
play = [
    { run = 'vlc "$@"', orphan = true },
]
ebook = [
    { run = 'ebook-viewer "$@"', orphan = true }
]

[open]
prepend_rules = [
    { name = "*.epub", use = "ebook" }
]
