source=./env.conf
source=./input.conf
source=./keybinds.conf
source=./tags.conf
source=./theme.conf
source=./window.conf

# uncomment to use noctalia
source=./noctalia.conf
exec-once=noctalia

# use either waybar or noctalia (don't use both)
# exec-once=waybar -c ~/.config/mango/waybar/config.jsonc -s ~/.config/mango/waybar/style.css
exec-once=/usr/lib/xdg-desktop-portal-wlr &
exec-once=fcitx5 --replace -d >/dev/null 2>&1 &
exec-once=swaybg -i ~/Pictures/Wallpapers/wallpaper.jpg
