bind=SUPER, d, spawn, noctalia msg panel-toggle launcher
bind=SUPER, s, spawn, noctalia msg panel-toggle control-center
bind=SUPER, c, spawn, noctalia msg caffeine-toggle
bind=SUPER, p, spawn, noctalia msg panel-toggle session
bind=SUPER, ESCAPE, spawn, noctalia msg session lock

bind=NONE, PRINT, spawn, noctalia msg screenshot-region
bind=SHIFT, PRINT, spawn, noctalia msg screenshot-fullscreen
bind=CTRL, PRINT, spawn, noctalia msg screenshot-fullscreen pick
bind=SUPER, PRINT, spawn, noctalia msg screenshot-fullscreen all
