borderpx=4
gappih=8
gappiw=8
gappoh=8
gappow=8

blur=0
blur_layer=0
blur_optimized=1
blur_params_num_passes=2
blur_params_radius=5
blur_params_noise=0.02
blur_params_brightness=0.9
blur_params_contrast=0.9
blur_params_saturation=1.0
layer_animations=0

shadows=1
layer_shadows=0
shadow_only_floating=0
shadows_size=4
shadows_blur=12
shadows_position_x=2
shadows_position_y=2
shadowscolor=0x000000ff

globalcolor=0xffffffff
focuscolor=0x71d23bff

cursor_size=24
cursor_theme=Bibata-Modern-Classic

blur=1
blur_layer=1
blur_optimized=1

border_radius=8
borderpx=4
focused_opacity=0.95
unfocused_opacity=0.65

animations=1
layer_animations=1

xwayland_persistence=1
syncobj_enable=1
no_border_when_single=0
