blur=0
blur_layer=1
blur_optimized=1

borderpx=4
gappih=8
gappiw=8
gappoh=8
gappow=8

shadows = 1
layer_shadows = 1
shadow_only_floating = 1
shadows_size = 18
shadows_blur = 22
shadows_position_x = 0
shadows_position_y = 4

globalcolor=0xffffffff
focuscolor=0x71d23bff

cursor_size=24
cursor_theme=Bibata-Modern-Classic

blur=1
blur_layer=1
blur_optimized=1

border_radius=8
borderpx=4
focused_opacity=0.95
unfocused_opacity=0.65

animations=1
layer_animations=1

xwayland_persistence=1
syncobj_enable=1
no_border_when_single=0
